services:
  db:
    image: postgres:16.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
      - minio
    networks:
      - app_network

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  minio_data:

networks:
  app_network:
    driver: bridge
