# Generated by Django 5.1.4 on 2025-01-10 10:45

import sales.storage_backends
import sales.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_alter_invoiceitem_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_method",
            field=models.CharField(
                choices=[
                    ("IPG", "Internet Payment Gateway"),
                    ("POS", "Point of Sale"),
                    ("CARD", "Card to Card"),
                    ("CASH", "Cash"),
                ],
                default="IPG",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=sales.storage_backends.ProductImageStorage(),
                upload_to="",
                validators=[sales.validators.validate_image_size],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceitem",
            unique_together={("invoice", "product")},
        ),
    ]
